# Generated by Django 6.0.3 on 2026-03-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("BOOK", "Livro"),
                            ("ARTICLE", "Artigo"),
                            ("VIDEO", "Vídeo"),
                            ("COURSE", "Curso"),
                            ("COURSE", "Ferramenta"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
