# Generated by Django 6.0.3 on 2026-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("BOOK", "Livro"),
                    ("ARTICLE", "Artigo"),
                    ("VIDEO", "Vídeo"),
                    ("COURSE", "Curso"),
                    ("COURSE", "Ferramenta"),
                    ("LINK", "Link"),
                    ("OTHER", "Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
