# Generated by Django 6.0.3 on 2026-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_profile_brand_profile_linkedin_profile_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="welcome_message",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Mensagem de Boas-vindas"
            ),
        ),
    ]
