# Generated by Django 6.0.3 on 2026-03-27 00:03

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to="posts/",
                variations={"medium": {"crop": False, "height": 201, "width": 246}},
            ),
        ),
    ]
