# Generated by Django 6.0.3 on 2026-03-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_posts_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
