# Generated by Django 6.0.3 on 2026-03-31 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_posts_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Posts",
            new_name="Post",
        ),
        migrations.RenameModel(
            old_name="Services",
            new_name="Service",
        ),
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
