# Generated by Django 6.0.3 on 2026-03-31 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_rename_posts_post_rename_services_service_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={"verbose_name": "E-mail", "verbose_name_plural": "E-mails"},
        ),
        migrations.AlterModelOptions(
            name="phone",
            options={"verbose_name": "Telefone", "verbose_name_plural": "Telefones"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfis"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Serviço", "verbose_name_plural": "Serviços"},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "verbose_name": "Habilidade",
                "verbose_name_plural": "Habilidades",
            },
        ),
        migrations.AlterField(
            model_name="skill",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="core.profile",
            ),
        ),
    ]
