# Generated by Django 6.0.3 on 2026-04-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_email_options_alter_phone_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biografia"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="message",
            field=models.TextField(blank=True, max_length=200, verbose_name="Mensagem"),
        ),
    ]
