# Generated by Django 6.0.3 on 2026-04-07 02:38

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_profile_bio_alter_profile_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to="skills/",
                variations={"medium": {"crop": False, "height": 55, "width": 108}},
            ),
        ),
    ]
