# Generated by Django 6.0.3 on 2026-04-07 13:47

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("backend", "Backend"),
                    ("arquitetura", "Arquitetura"),
                    ("dados", "Dados & Busca"),
                    ("devops", "DevOps"),
                    ("aprendizado", "Aprendizado"),
                    ("reflexoes", "Reflexões"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to="posts/",
                variations={"medium": {"crop": False, "height": 310, "width": 460}},
            ),
        ),
    ]
