# Generated by Django 6.0.3 on 2026-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_post_category_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("backend", "Backend"),
                    ("arquitetura", "Arquitetura"),
                    ("dados", "Dados & Busca"),
                    ("devops", "DevOps"),
                    ("aprendizado", "Aprendizado"),
                    ("reflexoes", "Reflexões"),
                    ("ferramentas", "Ferramentas"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
