# Generated by Django 6.0.3 on 2026-04-07 21:26

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_service_icon_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to="posts/",
                variations={"medium": {"crop": True, "height": 310, "width": 460}},
            ),
        ),
    ]
